# create your drupal and postgres config here, based off the last assignment
version: '3'
services: 
    drupal:
      build:
        context: .
        dockerfile: Dockerfile
      image: custom-drupal
      ports:
       - '80:80'
      volumes:
       - drupal-modules:/var/www/html/modules 
       - drupal-themes:/var/www/html/themes
       - drupal-sites:/var/www/html/sites
       - drupal-profiles:/var/www/html/profiles

    postgres:
      image: postgres:9.6 
      environment: 
        POSTGRES_PASSWORD: mypassword
      volumes: 
       - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-themes:
  drupal-sites:
  drupal-profiles:
  drupal-data:
